// Include all static modules here (modules that doesnt require an import to be useful)
import './key-events/key-events'
import './interfaces/interfaces'
import './player/player'
import './player/weaponcomponent'
import './player/crouching'
import './vehicle/vehicle'
import './apps/apps'
import './voice/voice'
import './doors/doors'
import './peds/vehiclesync'
import './peds/animalapi'
import './utils/bodyCamera'
import './rage11/rage11'
import './rage11/noclip'
import './vehicle/rappel'
import './player/welcomescene'
import './player/bigDataReceiver'